name: image_editing_app
description: A simple image editor with filters and saving capabilities

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  image_picker: ^0.8.7
  image: ^4.0.17
  image_gallery_saver: ^2.1.1
  permission_handler: ^10.2.0
  path_provider: ^2.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/